// <auto-generated />
using MicroQueue.Consumer.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MicroQueue.Consumer.Data.Migrations
{
    [DbContext(typeof(ConsumerDbContext))]
    [Migration("20230615202530_Initial Migration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MicroQueue.Consumer.Domain.Models.MailQueue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("varchar(MAX)");

                    b.Property<string>("IdUsuarioLog")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<string>("MessageResponse")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<int>("StatusResponse")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MailQueues");
                });

            modelBuilder.Entity("MicroQueue.Consumer.Domain.Models.ManifiestoQueue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("IdUsuarioLog")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<string>("JsonMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageResponse")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Printer")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<int>("StatusResponse")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ManifiestoQueues");
                });
#pragma warning restore 612, 618
        }
    }
}
